name: Release

on:
  workflow_dispatch:
jobs:
  release-nightly:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
        with:
          ref: master
          fetch-depth: 0

      - name: Execute Build and Deploy
        uses: fabernovel/docker-android@v1.4.1
        with:
          docker-android-tag: api-29-ndk-v1.1.0
          exec: |
            bundle install;
            bundle exec fastlane build_and_deploy;